image: golang:1.16

services:
  - redis:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DEBIAN_FRONTEND: noninteractive

cache:
  paths:
    - /apt-cache
    - /go/pkg/mod

stages:
  - test

unit_tests:
  stage: test
  before_script:
    # Install project dependencies
    - make dep
    - make plugins
  script:
    - make test
    - KIPROTECT_TEST_API_SETTINGS=`readlink -f testing/api/settings`:`readlink -f testing/api/settings/gitlab` make test-api
